<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ag_project"
 *
 * Auto generated by Extension Builder 2016-02-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Project Managment',
	'description' => 'Project managment with isotop or pagination option',
	'category' => 'plugin',
	'author' => 'Ajay Gohel',
	'author_email' => 'ajaygohel30@gmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.0.1',
	'constraints' => array(
		'depends' => array(
			'vhs' => '',
            'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);